-- Run this migration in Supabase SQL Editor after reviewing the duplicate report.
-- Duplicate attendance rows are reduced by retaining the newest updated record.

begin;

create temporary table aesa_attendance_duplicates as
select
    student_id,
    subject_id,
    academic_year,
    count(*) as duplicate_count
from public.attendance
group by student_id, subject_id, academic_year
having count(*) > 1;

-- Review this result before the delete when running the migration manually:
select * from aesa_attendance_duplicates;

with ranked as (
    select
        id,
        row_number() over (
            partition by student_id, subject_id, academic_year
            order by updated_at desc nulls last, created_at desc nulls last, id desc
        ) as row_number
    from public.attendance
)
delete from public.attendance as attendance
using ranked
where attendance.id = ranked.id
  and ranked.row_number > 1;

create unique index if not exists attendance_student_subject_year_key
    on public.attendance (student_id, subject_id, academic_year)
    where subject_id is not null;

create unique index if not exists attendance_student_growth_year_key
    on public.attendance (student_id, academic_year)
    where subject_id is null;

create table if not exists public.communication_history (
    id bigint generated by default as identity primary key,
    student_id uuid null references public.students(id) on delete set null,
    student_name text not null,
    student_email text,
    parent_email text not null,
    attendance_percentage numeric(5, 2) not null,
    subject text not null,
    message text not null,
    communication_type text not null default 'Email',
    status text not null default 'Sent',
    message_id text,
    mentor_name text,
    mentor_email text,
    sent_at timestamptz not null default now()
);

create index if not exists communication_history_sent_at_idx
    on public.communication_history (sent_at desc);

commit;
